#!/bin/bash

FILEID='1gYiv3V06Q-S1MWzJpIlx6Jmf2Je-mUwL'
TARGET='rover_description/meshes/'
echo 'Downloading Meshes'

$(which python3) -m pip install gdown
gdown --id $FILEID
echo 'Download Complete'

mkdir -p $TARGET 
tar -xvf meshes.tar.gz --directory=$TARGET
echo 'Extraction Complete'

rm -f meshes.tar.gz
echo 'Directory Clean'

