<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mrover_arm">
    <virtual_joint name="" type="fixed" parent_frame="world" child_link="chassis-a" />

    <xacro:property name="PI" value="3.141592" />
    <xacro:property name="base_width" value="7" />
    <xacro:property name="base_len" value="7" />
    <xacro:property name="base_height" value="7" />

    <xacro:macro name="link-visual" params="fileName x y z col r g b roll:=0 pitch:=0 yaw:=0">
        <visual>
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}" />
            <geometry>
                <mesh filename="package://mrover/rover_description/arm/${fileName}" />
            </geometry>
            <material name="${col}">
                <color rgba="${r} ${g} ${b} 1" />
            </material>
        </visual>
    </xacro:macro>

    <xacro:macro name="link-inertial" params="x:=0 y:=0 z:=0 roll:=0 pitch:=0 yaw:=0 mass ixx iyy izz ixy:=0 iyz:=0 ixz:=0">
        <inertial>
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}" />
            <!-- mass in kg -->
            <mass value="${mass}" />
            <inertia ixx="${ixx}" iyy="${iyy}" izz="${izz}" ixy="${ixy}" iyz="${iyz}" ixz="${ixz}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}" />
    </inertial>
  </xacro:macro>

    <!-- defines a cylinder collision object with two endpoints -->
    <xacro:macro name="link-collision-cylinder" params="radius x1 y1 z1 x2 y2 z2 roll:=0 pitch:=0 yaw:=0">
        <xacro:property name="dx" value="${x2-x1}" />
        <xacro:property name="dy" value="${y2-y1}" />
        <xacro:property name="dz" value="${z2-z1}" />

        <xacro:if value="${dx != 0}">
            <xacro:property name="length" value="${fabs(dx)}" />
            <xacro:property name="rpy" value="${roll} ${pitch+PI/2} ${yaw}" />
        </xacro:if> 
        <xacro:if value="${dy != 0}">
            <xacro:property name="length" value="${fabs(dy)}" />
            <xacro:property name="rpy" value="${roll+PI/2} ${pitch} ${yaw}" />
        </xacro:if>
        <xacro:if value="${dz != 0}">
            <xacro:property name="length" value="${fabs(dz)}" />
            <xacro:property name="rpy" value="${roll} ${pitch} ${yaw}" />
        </xacro:if>

        <collision>
            <origin xyz="${x1+dx/2} ${y1+dy/2} ${z1+dz/2}" rpy="${rpy}" />
            <geometry>
                <cylinder radius="${radius}" length="${length}" />
            </geometry>
        </collision>
    </xacro:macro>

    <!-- defines a box collision object with the center and dimensions -->
    <xacro:macro name="link-collision-box" params="x:=0 y:=0 z:=0 lx ly lz roll:=0 pitch:=0 yaw:=0">
        <collision>
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}" />
            <geometry>
                <box size="${lx} ${ly} ${lz}" />
            </geometry>
        </collision>
    </xacro:macro>

    <xacro:macro name="joints" params="name type:=revolute parent child roll:=0 pitch:=0 yaw:=0 origin_x origin_y origin_z axis_x:=0 axis_y:=0 axis_z:=0 lower upper damp:=1.0" >
        <joint name="${name}" type="${type}">
            <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="${roll} ${pitch} ${yaw}" />
            <parent link="${parent}" />
            <child link="${child}" />
            <axis xyz="${axis_x} ${axis_y} ${axis_z}" />
            <!-- effort in N-m, velocity in rad/s -->
            <limit lower="${lower}" upper="${upper}" effort="30" velocity="1" />
            <!-- damping in N-m-s/rad -->
            <dynamics damping="${damp}" />
        </joint>
    </xacro:macro>

    <xacro:macro name="gazebo_ref" params="link">
        <gazebo reference="${link}">
            <material>Gazebo/White</material>
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
            <selfCollide>false</selfCollide>
        </gazebo>
   </xacro:macro>

    <xacro:macro name="transmissions" params="name">
        <transmission name="trans_${name}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <link name="chassisToa">
        <xacro:link-visual fileName="chassis-a.stl" x="0" y="0" z="0" col="red" r="1" g="0" b="0"/>
        <xacro:link-collision-cylinder radius="3.75" x1="0" y1="0" z1="-1.25" x2="0" y2="0" z2="-3.75" />
        <xacro:link-collision-cylinder radius="1.75" x1="3.6467207" y1="3.6590503" z1="1" x2="3.6467207" y2="3.6590503" z2="-2.6913988" />
        <!-- calculated based on cylinder1 -->
        <xacro:link-inertial z="-2.5" mass="0.5" ixx="2.3" iyy="2.3" izz="3.5" />
    </link>
    <link name="aTob">
        <xacro:link-visual fileName="a-b.stl" x="0" y="0" z="0" col="orange" r="1" g="0.43" b="0" roll="0"/>
        <xacro:link-collision-box y="-1.75" z="3" lx="2" ly="3" lz="6" />
        <xacro:link-collision-cylinder radius="2" x1="0" y1="0" z1="-0.25" x2="0" y2="0" z2="0.75" />
        <xacro:link-inertial y="-1.75" z="3" mass="0.5" ixx="1.9" iyy="0.7" izz="0.5" />
    </link>
    <link name="bToc">
        <xacro:link-visual fileName="b-c.stl" x="0" y="0" z="0" col="yellow" r="1" g="1" b="0" roll="0"/>
        <xacro:link-collision-box y="9" z="5" lx="3" ly="24" lz="3" roll="0.48" />
        <xacro:link-collision-cylinder radius="2" x1="-2" y1="20.25" z1="10.75" x2="4.5" y2="20.25" z2="10.75" />
        <xacro:link-collision-cylinder radius="1" x1="0" y1="-2" z1="8.5" x2="0" y2="17" z2="8.5" roll="0.3" />
        <xacro:link-inertial y="12" mass="0.5" ixx="24" iyy="0.75" izz="24" />
    </link>
    <link name="cTod">
        <xacro:link-visual fileName="c-d.stl" x="0" y="0" z="0" col="green" r="0.43" g="1" b="0"/>
        <xacro:link-collision-cylinder radius="3.75" x1="-4.5" y1="0" z1="-2.5" x2="-4.5" y2="0" z2="3" roll="-0.17"/>
        <xacro:link-inertial x="-1" mass="0.5" ixx="3.2" iyy="3.2" izz="16" />
    </link>
    <link name="dToe">
        <xacro:link-visual fileName="d-e.stl" x="0" y="0" z="0" col="blue" r="0" g="0" b="1" pitch="0" roll="0"/>
        <xacro:link-collision-box y="0" z="-7" lx="4" ly="20" lz="4" roll="${(-PI/2.0)+0.05}"/>
        <xacro:link-collision-cylinder radius="2.5" x1="-3" y1="0" z1="-17" x2="3" y2="0" z2="-17" />
        <xacro:link-inertial y="-7.6324" z="4.7693" roll="-0.558505" mass="0.5" ixx="17" iyy="0.5" izz="17" />
    </link>
    <link name="eTof">
        <xacro:link-visual fileName="e-f.stl" x="0" y="0" z="0" col="violet" r="0.5" g="0" b="1" roll="0" />
        <xacro:link-collision-cylinder radius="3" x1="3" y1="1.8" z1="0" x2="-6.5" y2="1.8" z2="0" />
        <xacro:link-inertial z="-3" mass="0.5" ixx="1.6" iyy="1.6" izz="0.25" />
    </link>
    <link name="hand">
        <xacro:link-visual fileName="hand.stl" x="0" y="0" z="0" col="pink" r="1" g="0" b="1"/>
        <xacro:link-collision-box x="-2.25" y="1" z="0.5" lx="8" ly="3.5" lz="8.5" roll="${PI/2.0}"/>
        <xacro:link-collision-box z="8.75" y="3.5" x="-1" lx="3.5" ly="3.5" lz="5" roll="${PI/2.0}"/>
        <xacro:link-collision-cylinder radius="0.75" x1="0" y1="2.3" z1="0" x2="0" y2="2.3" z2="9"/>
        <xacro:link-collision-box x="-1.6" y="-1.5" z="-2" lx="1" ly="2.5" lz="2.5"/>
        <xacro:link-inertial z="-2.5" mass="0.5" ixx="2.2" iyy="4" izz="2.2" />
    </link>

    <link name="world" />
    <joint name="virtual_joint" type="fixed">
        <parent link="world" />
        <child link="chassisToa" />
        <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
    </joint>

    <xacro:joints name="joint_a" type="continuous" parent="chassisToa" child="aTob" origin_x="0" origin_y="0" origin_z="0" axis_z="1" lower="-3.14" upper="3.14" />
    <xacro:joints name="joint_b" parent="aTob" child="bToc" origin_x="0" origin_y="1.33" origin_z="0.99" axis_x="1" lower="-1.064651" upper="0" roll="0.593412"/>
    <xacro:joints name="joint_c" parent="bToc" child="cTod" origin_x="0" origin_y="20.11" origin_z="10.75" axis_x="1" lower="-0.087267" upper="4.886922" roll="-0.436332"/>
    <xacro:joints name="joint_d" parent="cTod" child="dToe" origin_x="-4.4" origin_y="-0.42" origin_z="-2.535" axis_z="1" axis_y="0" lower="-3.14" upper="3.14" roll="-0.15708" pitch="-0.0174533" yaw="0" />
    <xacro:joints name="joint_e" parent="dToe" child="eTof" origin_x="2.55" origin_y="0.2" origin_z="-17" axis_y="1" lower="-3.59538" upper="0.610865" roll="0" pitch="0" yaw="-1.649336"/>
    <xacro:joints name="joint_f" parent="eTof" child="hand" origin_x="-6.3" origin_y="1.75" origin_z="0" axis_x="1" lower="-0.523599" upper="6.28" />
    <xacro:transmissions name="joint_a" />
    <xacro:transmissions name="joint_b" />
    <xacro:transmissions name="joint_c" />
    <xacro:transmissions name="joint_d" />
    <xacro:transmissions name="joint_e" />
    <xacro:transmissions name="joint_f" />

    <xacro:gazebo_ref link="chassisToa" />
    <xacro:gazebo_ref link="aTob" />
    <xacro:gazebo_ref link="bToc" />
    <xacro:gazebo_ref link="cTod" />
    <xacro:gazebo_ref link="dToe" />
    <xacro:gazebo_ref link="eTof" />
    <xacro:gazebo_ref link="hand" />

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so" />
    </gazebo>
    
</robot>