#!/bin/bash

pushd deps/dawn || exit
CC=clang CXX=clang++ cmake -B out/Release -G Ninja -D DAWN_FETCH_DEPENDENCIES=ON -D CMAKE_BUILD_TYPE=RelWithDebInfo -D DAWN_ENABLE_DESKTOP_GL=OFF -D DAWN_ENABLE_OPENGLES=OFF -D DAWN_ENABLE_NULL=OFF -D DAWN_BUILD_SAMPLES=OFF -D TINT_BUILD_DOCS=OFF -D TINT_BUILD_TESTS=OFF -D DAWN_ENABLE_INSTALL=ON -D BUILD_SHARED_LIBS=ON
cmake --build out/Release
