# Generated by Django 4.2.7 on 2024-01-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ("tag_id", models.IntegerField()),
                ("type", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
